id: P3700658F
initial_creation_type: ocr
source_metadata:
  volumes:
    72740f2cb9c147f0be2ae7fd4822db94:
      base_file: v017.txt
      image_group_id: I1PD95862
      title: སྒྲོན་མ་གསལ་བ་ཞེས་བྱ་བའི་འགྲེལ་བཤད།
      total_pages: 1158
      volume_number: 17
